src/app/(home)/_components/LandingPage.tsx, src/app/test/page.tsx, src/components/Button/Button.tsx, src/components/Header/Header.tsx, src/styles/tokens.css
- 버튼 컴포넌트 버튼 속성 받도록 하여 기본 속성 확장하도록 수정
- svg를 지정된 애들만 하면 추후에 확장이 어려우니 외부에서 svg 컴포넌트 넘겨주도록 수정
- theme로 클래스명 되도록 수정
- 디자인 토큰에서 간경명 변경
- 사용방법은 크게 달라지지 않지만 사용처에서 SVG컴포넌트를 넘기도록 하였습니다 test페이지에 적용시켰습니다 확인 부탁드립니다
=> refactor: 공통 버튼 컴포넌트 수정

Dockerfile, next.config.mjs, tsconfig.json
- Dockerfile 추가
- baseUrl 설정 추가
- 배포 정상 동작 여부 확인
- kakao redirect url 변경요청 (상현님)
=> feat: Dockerfile 추가

.github/workflows/cd.yml
=> feat: 배포 workflow 추가

src/apis/instance/APIClient.ts, src/app/rehearsal/_components/Main/_components/CompleteModal/index.tsx, src/app/rehearsal/_components/Video/Video.module.css, src/components/Button/Button.module.css, src/components/Header/index.tsx, src/components/LayoutWrapper/index.tsx, src/constants/isDark.ts, src/constants/path.ts, src/middleware.ts, src/utils/cookies.ts
- APIClient 에러메시지 수정
- 쿠키 기본 옵션 수정
- 버튼 컴포넌트 가운데 정렬수정
- 비디오 좌우 반전
- 미들웨어로 리허설, 결과 페이지 쿠키없으면 404로 리다이렉트 설정
=> refactor: 전반적인 리팩토링

src/apis/answer.ts, src/apis/question.ts, src/app/result/_components/AnswerList/index.tsx, src/app/result/_components/KeywordList/index.tsx, src/app/result/_components/Question/index.tsx, src/app/result/page.tsx, src/constants/path.ts, src/stores/devicsStore.ts
- fetch 캐싱 제거
- 윈도우에서만 디바이스 호출하도록 수정
=> refactor: 기본적인 리팩토링

src/app/401/page.tsx, src/app/403/page.tsx, src/app/500/error.tsx, src/app/not-found.tsx, src/middleware.ts
- 에러 관련된 페이지 작성
- result, rehearsal 페이지 로그인 안하고 입장시 401로 리다이렉트
=> feat: error페이지작성

src/apis/instance/APIClient.ts, src/app/users/_components/steps/JoinEmailVerification.tsx, src/app/users/join/page.tsx, src/app/users/oauth/kakao/page.tsx, src/components/LayoutWrapper/index.tsx, src/components/Modal/ModalClient.tsx, src/components/Modal/index.tsx, src/components/TokenExpirationHandler.tsx, src/stores/modalStore.ts
-JWT 토큰 관련된 커스텀 에러 트리거해서 에러 핸들링
- window 기본 모달이 아닌 커스텀 모달로 핸들링 작성
- 이후 할 일을
- 적어주세요
=> refactor: 커스텀 모달로 에러 모달 핸들링

.github/workflows/cd.yml
- google analytics 환경변수 추가
- 회원가입 이메일인증 redirect 환경변수 추가
=> deploy: workflow에 환경변수 추가

src/contexts/UserJoinProvider.tsx
=> fix: [회원가입] 다음 버튼 예외처리 추가

src/app/(blackbg)/rehearsal/_components/Main/_components/Buttons/index.tsx, src/app/(blackbg)/rehearsal/_components/Main/_components/Contents/index.tsx, src/app/(blackbg)/rehearsal/_components/Setting/index.tsx, src/app/(whitebg)/minari/page.tsx, src/app/(whitebg)/result/_components/KeywordList/index.tsx, src/app/(whitebg)/result/_components/Question/index.tsx, src/app/(whitebg)/result/page.tsx, src/constants/questionId.ts
- 버튼 disabled 처리 작업 진행
- question id 상수처리
- 이후 할 일을
- 적어주세요
=> refactor: 버튼 disabled 처리 작업 진행

.github/workflows/cd.yml, .github/workflows/ci.yml, .idea/workspace.xml
- NEXT_PUBLIC_API_URL_ADMIN 추가
(어드민 api url)
=> feat: workflow에 환경변수추가

package.json
=> [DEPLOY] staging 버전 업데이트

src/app/(blackbg)/rehearsal/_components/Setting/_components/OptionGroup/index.tsx, src/components/Button/Button.module.css, src/components/Button/index.tsx, src/components/Modal/Model.module.css, src/components/Modal/hooks/useErrorModal.tsx, src/components/Modal/index.tsx, src/constants/path.ts, src/hooks/useMedia.tsx, src/utils/media.ts
- 미디어스트림 연결 상태에 따른 모달
- 버튼 full props추가
- 모달 사이즈 조절
- 미디어스트림 에러시 리허설 페이지로 이동버튼 disabled
=> refactor: 미디어스트림 연결 상태에 따른 모달 처리

src/app/(whitebg)/users/seeds/_components/QRCodeModal/QRCodeModal.module.css, src/app/(whitebg)/users/seeds/_components/QRCodeModal/QRCodeModalRefund.tsx, src/app/(whitebg)/users/seeds/_components/QRCodeModal/index.tsx
=> Feat: 환불 모달 작성

src/apis/payment.ts, src/apis/seeds.ts, src/app/admin/_components/PageLayout.module.css, src/app/admin/page.tsx, src/app/admin/payments/_components/CheckModal.tsx, src/app/admin/payments/page.tsx, src/components/Header/index.tsx, src/hooks/queries/useProducts.ts, src/hooks/queries/useSeeds.ts
- [어드민] 씨앗 지급 api 규격 수정내용 반영
- [어드민] 씨앗지급 인풋 -> 셀렉트박스로 수정
=> FEAT: [어드민] 씨앗 지급 api 규격 수정내용 반영

src/apis/products.ts, src/app/(whitebg)/users/seeds/_components/(tabs)/BuyTab.tsx, src/app/(whitebg)/users/seeds/_components/(tabs)/HistoryTab.tsx
- 필드 수정 및 반영
- 이후 할 일을
- 적어주세요
=> refactor: 필드 수정 및 반영

package.json
=> deploy: 메인 v0.3.0 배포

package.json, src/apis/question.ts, src/app/(whitebg)/minari/Minari.module.css, src/app/(whitebg)/minari/_components/Detail/Detail.module.css, src/app/(whitebg)/minari/_components/Detail/index.tsx, src/app/(whitebg)/minari/page.tsx, src/hooks/queries/useTagDetail.ts
=> Feat: 미나리 페이지 세부 카테고리 API 적용

src/app/(whitebg)/users/my/_components/Tab/Info/index.tsx, src/hooks/useDate.ts
=> fix: 잔디밭 undefined 이슈 수정

package.json, pnpm-lock.yaml, src/app/(whitebg)/users/my/_components/Heatmap/Blocks/Blocks.module.css, src/app/(whitebg)/users/my/_components/Heatmap/Blocks/index.tsx, src/contexts/UserHeatmapProvider.tsx, src/hooks/useDate.ts
=> Issue/마이페이지 툴팁

src/contexts/UserHeatmapProvider.tsx
=> refactor: 불필요 콘솔 로그 삭제

package.json
=> deploy: v0.5.0 배포

ads.txt, src/app/layout.tsx
- 구글 애드센스 연동 재작업
- 연동 성공 여부 재확인
=> feat: 구글 에드센스 연동 재작업

src/app/(home)/_components/TextSlider/index.tsx, src/app/(home)/page.tsx, src/app/(whitebg)/users/join/_components/JoinCompleted.tsx, src/app/(whitebg)/users/join/page.tsx, src/app/(whitebg)/users/my/_components/Heatmap/BlockDetail/BlockDetail.module.css, src/app/(whitebg)/users/my/_components/Heatmap/BlockDetail/index.tsx, src/app/(whitebg)/users/my/_components/Heatmap/Blocks/Blocks.module.css, src/app/(whitebg)/users/my/_components/Heatmap/Blocks/index.tsx, src/app/(whitebg)/users/my/_components/ProfileCard/ProfileCard.module.css, src/app/(whitebg)/users/my/_components/ProfileCard/index.tsx, src/app/(whitebg)/users/my/_components/Tab/Info/index.tsx, src/app/(whitebg)/users/my/page.module.css, src/app/(whitebg)/users/my/page.tsx, src/components/Footer/index.tsx, src/components/Header/Header.module.css, src/hooks/useConvert.ts
- [메인] 텍스트 수정 / 미나리 아이콘 크기 고정
- [공통] Footer: help 메일주소 수정
- [마이페이지] 프로필 기본 이미지 -> 카톡 프사로 변경
- [마이페이지] 화면비율, 잔디밭 크기 수정
- [마이페이지] 잔디 상세보기 키워드 길때 화면 깨짐 수정
- [공통] Header, 마이페이지 프로필사진 비율 깨짐 수정
- [로그인] 로그인 시 탈퇴유저 처리 로직 추가
=> [FIX] UT 피드백 내용 반영

src/app/(whitebg)/rehearsal/result/hooks/usePromotionsModal.tsx
=> refactor: 모달 분기 수정

src/app/(whitebg)/users/my/_components/Heatmap/Blocks/Blocks.module.css, src/components/InfoBox/InfoBox.module.css
- [마이페이지] 폰트 깨짐 수정
- [공통] info wrapper css 수정
=> [FIX] 화면 깨짐 수정

package.json
=> deploy: v0.10.1 배포

src/app/(whitebg)/test/page.tsx, src/app/(whitebg)/users/seeds/_components/(tabs)/BuyTab.tsx, src/app/(whitebg)/users/seeds/_components/(tabs)/HistoryTab.tsx, src/components/TossPaymentWidget/index.tsx, src/utils/getRandomString.ts
- 씨앗페이지에서 토스 위젯 나오도록 수정
- orderId 주문건당 고유값으로 수정
- 이후 할 일을
- 적어주세요
=> feat: 씨앗 페이지에 토스 위젯 나오도록 설정

src/app/(whitebg)/minari/_components/MainButton/MainButton.module.css, src/app/(whitebg)/minari/_components/MainButton/index.tsx, src/app/(whitebg)/rehearsal/result/_components/Keyword/Keywrod.module.css, src/app/(whitebg)/rehearsal/result/_components/Keyword/index.tsx, src/app/(whitebg)/rehearsal/result/_components/ListRow/ListRow.module.css, src/app/(whitebg)/rehearsal/result/_components/ListRow/index.tsx, src/styles/tokens.css
- 미나리페이지 버튼 반응형
- 리허설 결과페이지 반응형
- 이후 할 일을
- 적어주세요
=> feat: 반응형 미나리, 리허설 페이지

src/apis/toss.ts, src/app/(whitebg)/payment/loading/page.tsx, src/app/(whitebg)/payment/success/page.tsx, src/app/(whitebg)/test/jsonparam/page.tsx, src/app/(whitebg)/test/page.tsx, src/components/TossPaymentWidget/index.tsx, src/hooks/queries/useTossPayments.ts
- 파라미터 json으로 보여주는 테스트페이지 추가
- 결제 성공시 getAPI 연동
- loading페이지 파라미터 받는 로직 수정
- 이후 할 일을
- 적어주세요
=> feat: 파라미터 JSON으로 보여주는 페이지 추가, 결제 결과 받을수 있도록 추가

src/app/(whitebg)/users/my/_components/Heatmap/Block/index.tsx, src/app/(whitebg)/users/my/_components/Heatmap/BlockTab/BlockTab.module.css, src/app/(whitebg)/users/my/_components/Heatmap/BlockTab/index.tsx, src/app/(whitebg)/users/my/_components/Heatmap/Blocks/Blocks.module.css, src/app/(whitebg)/users/my/_components/Heatmap/Blocks/index.tsx, src/app/(whitebg)/users/my/_components/Tab/More/More.module.css, src/app/(whitebg)/users/my/_components/Tab/More/index.tsx, src/app/(whitebg)/users/my/page.module.css, src/contexts/UserHeatmapProvider.tsx
=> feat: [마이페이지] 반응형 작업

src/hooks/useMicVolume.ts
- 사운드바 음향 계산 interval에서 requestAnimationFrame으로 애니메이션 성능 개선
- 이후 할 일을
- 적어주세요
=> refactor: requestAnimationFrame으로 애니메이션 성능 개선
